---
- hosts: worker
  become: true
  become_method: sudo
  gather_facts: false
  
  tasks: 
    - name: git clone repo
      shell: git clone https://github.com/LimeChain/hedera-eth-bridge-validator.git
      register: result
      ignore_errors: yes
      
    - name: docker-compose down
      shell: docker-compose down;docker ps -a
      
    - name: taking the backup of yml's - bridge.yml node.yml docker-compose.yml
      shell: cd /home/sunil/hedera-eth-bridge-validator;DATE=`date "+%Y%m%d"`;cp bridge.yml bridge-$DATE.yml; cp node.yml node-$DATE.yml; cp docker-compose.yml docker-compose-$DATE.yml
      
    #- name: changing and replace the image string and image version  
    #  lineinfile:
    #    path: /home/sunil/hedera-eth-bridge-validator/docker-compose.yml
    #    regexp: 'image: gcr.io/hedera-eth-bridge-test/hedera-eth-bridge-validator:${TAG}'
    #    line: 'image: gcr.io/hedera-eth-bridge-test/hedera-eth-bridge-validator:v0.0.4-rc-3'
    #    owner: root
    #    group: root
    #    mode: 0644
    #    backup: no
    - name: changing and replace the image string and image version  
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '${TAG}$'
        replace: 'v0.0.4-rc-3'
      
    - name: git clone repo
      shell: cd hedera-eth-bridge-validator;docker-compose up -d
      register: result
    
