---
- hosts: worker
  become: true
  become_method: sudo
  gather_facts: false
  
  tasks: 
    - name: git clone repo
      shell: git clone https://github.com/LimeChain/hedera-eth-bridge-validator.git
      register: result
      ignore_errors: yes
    - name: git clone repo
      shell: cd hedera-eth-bridge-validator;docker-compose up -d
      register: result
      
    - name: taking the backup of yml's - bridge.yml node.yml docker-compose.yml
      shell: cp bridge.yml bridge-$(date -j -f "%d-%m-%Y").yml; cp node.yml node-$(date -j -f "%d-%m-%Y").yml; cp docker-compose.yml docker-compose-$(date -j -f "%d-%m-%Y").yml
      
    - name: Print uptime of managed node
      debug:
        msg: "{{ result }}"  
    
