---
- hosts: worker
  become: true
  become_method: sudo
  gather_facts: false
  
  tasks: 
    - name: git clone repo
      shell: git clone https://github.com/LimeChain/hedera-eth-bridge-validator.git
      register: result
      ignore_errors: yes
      
    - name: docker-compose down
      shell: docker-compose down;docker ps -a
      
    - name: taking the backup of yml's - bridge.yml node.yml docker-compose.yml
      shell: cd /home/sunil/hedera-eth-bridge-validator;DATE=`date "+%Y%m%d"`;cp bridge.yml bridge-$DATE.yml; cp node.yml node-$DATE.yml; cp docker-compose.yml docker-compose-$DATE.yml
      
    - name: git clone repo
      shell: cd hedera-eth-bridge-validator;docker-compose up -d
      register: result
    
